<a href="https://colab.research.google.com/github/Aybarineecm/Data-Science--Analysis-of-the-THE-World-University-Rankings-2016-2024/blob/main/Data_Science_Analysis_of_the_THE_World_University_Rankings_2016_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('THE World University Rankings 2016-2024.csv', encoding= "latin1")

Displaying the first five rows of the dataset.

In [ ]:
df.head(5)

,Rank,Name,Country,Student Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,1.0,California Institute of Technology,United States,2243,6.9,26%,33 : 67,95.2,95.6,97.6,99.8,97.8,64.0,2016
1,2.0,University of Oxford,United Kingdom,19920,11.6,34%,46:54:00,94.2,86.5,98.9,98.8,73.1,94.4,2016
2,3.0,Stanford University,United States,15596,7.8,22%,42:58:00,93.9,92.5,96.2,99.9,63.3,76.3,2016
3,4.0,University of Cambridge,United Kingdom,18810,11.8,34%,46:54:00,92.8,88.2,96.7,97.0,55.0,91.5,2016
4,5.0,Massachusetts Institute of Technology,United States,11074,9.0,33%,37 : 63,92.0,89.4,88.6,99.7,95.4,84.0,2016

Displaying the last five rows of the dataset.

In [ ]:
df.tail(5)

,Rank,Name,Country,Student Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
12425,1900.0,Penza State University,Russian Federation,17934,17.2,12%,56:44:00,12.1935,14.3,8.7,7.8,16.3,32.8,2024
12426,1901.0,Universidad Peruana de Ciencias Aplicadas (UPC),Peru,56595,21.1,1%,50:50:00,12.1470,13.5,8.7,10.1,15.6,26.5,2024
12427,1902.0,Universidade Federal Rural do Semi-Arido,Brazil,8687,12.4,0%,49:51:00,11.9910,19.1,9.0,5.7,16.6,18.3,2024
12428,1903.0,State University of Bahia,Brazil,25067,11.9,0%,66:34:00,11.5655,19.3,8.6,4.1,16.2,20.0,2024
12429,1904.0,Tula State University,Russian Federation,18428,35.0,3%,60:40:00,9.6910,11.6,9.0,5.1,17.6,19.0,2024

Showing how many rows have missing values.

In [ ]:
df.isnull()

,Rank,Name,Country,Student Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12425,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12426,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12427,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12428,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12429,False,False,False,False,False,False,False,False,False,False,False,False,False,False

 Removing any row that has missing values.

In [ ]:
df.dropna()

,Rank,Name,Country,Student Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,1.0,California Institute of Technology,United States,2243,6.9,26%,33 : 67,95.2000,95.6,97.6,99.8,97.8,64.0,2016
1,2.0,University of Oxford,United Kingdom,19920,11.6,34%,46:54:00,94.2000,86.5,98.9,98.8,73.1,94.4,2016
2,3.0,Stanford University,United States,15596,7.8,22%,42:58:00,93.9000,92.5,96.2,99.9,63.3,76.3,2016
3,4.0,University of Cambridge,United Kingdom,18810,11.8,34%,46:54:00,92.8000,88.2,96.7,97.0,55.0,91.5,2016
4,5.0,Massachusetts Institute of Technology,United States,11074,9.0,33%,37 : 63,92.0000,89.4,88.6,99.7,95.4,84.0,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12425,1900.0,Penza State University,Russian Federation,17934,17.2,12%,56:44:00,12.1935,14.3,8.7,7.8,16.3,32.8,2024
12426,1901.0,Universidad Peruana de Ciencias Aplicadas (UPC),Peru,56595,21.1,1%,50:50:00,12.1470,13.5,8.7,10.1,15.6,26.5,2024
12427,1902.0,Universidade Federal Rural do Semi-Arido,Brazil,8687,12.4,0%,49:51:00,11.9910,19.1,9.0,5.7,16.6,18.3,2024
12428,1903.0,State University of Bahia,Brazil,25067,11.9,0%,66:34:00,11.5655,19.3,8.6,4.1,16.2,20.0,2024
12429,1904.0,Tula State University,Russian Federation,18428,35.0,3%,60:40:00,9.6910,11.6,9.0,5.1,17.6,19.0,2024

Renaming the column Student Population to Population

In [ ]:
df= df.rename(columns={'Student Population': 'Population'})

Display the country and name of all the universities that have more than 20,000 students

In [ ]:
df.head()

,Rank,Name,Country,Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,1.0,California Institute of Technology,United States,2243,6.9,26%,33 : 67,95.2,95.6,97.6,99.8,97.8,64.0,2016
1,2.0,University of Oxford,United Kingdom,19920,11.6,34%,46:54:00,94.2,86.5,98.9,98.8,73.1,94.4,2016
2,3.0,Stanford University,United States,15596,7.8,22%,42:58:00,93.9,92.5,96.2,99.9,63.3,76.3,2016
3,4.0,University of Cambridge,United Kingdom,18810,11.8,34%,46:54:00,92.8,88.2,96.7,97.0,55.0,91.5,2016
4,5.0,Massachusetts Institute of Technology,United States,11074,9.0,33%,37 : 63,92.0,89.4,88.6,99.7,95.4,84.0,2016

Display the country and name of all the universities that have more than 20,000 students

In [ ]:
df[

    df['Population']>20000][['Country', 'Name', 'Population']

    ]

,Country,Name,Population
5,United States,Harvard University,20152
12,United States,"University of California, Berkeley",36186
13,United Kingdom,UCL,26605
14,United States,Columbia University,25055
15,United States,"University of California, Los Angeles",38206
...,...,...,...
12416,Algeria,University Abdelhamid Ibn Badis Mostaganem,24983
12418,Japan,Toyo University,30662
12421,Colombia,Pedagogical and Technological University of Co...,33268
12426,Peru,Universidad Peruana de Ciencias Aplicadas (UPC),56595
12428,Brazil,State University of Bahia,25067

Filter all the rows that have Student to Staff ratio higher than 10 and an overall score greater than 60.

In [ ]:
df[
     (df['Students to Staff Ratio']>10) & (df['Overall Score']>60)

     ]

,Rank,Name,Country,Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
1,2.0,University of Oxford,United Kingdom,19920,11.6,34%,46:54:00,94.2000,86.5,98.9,98.8,73.1,94.4,2016
3,4.0,University of Cambridge,United Kingdom,18810,11.8,34%,46:54:00,92.8000,88.2,96.7,97.0,55.0,91.5,2016
7,8.0,Imperial College London,United Kingdom,15060,11.7,51%,37 : 63,89.1000,83.3,88.5,96.7,53.7,96.0,2016
8,9.0,ETH Zurich,Switzerland,18178,14.7,37%,31 : 69,88.3000,77.0,95.0,91.1,80.0,97.9,2016
12,13.0,"University of California, Berkeley",United States,36186,16.4,15%,50:50:00,87.2000,80.4,91.1,99.7,47.9,61.9,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10702,177.0,University of Ottawa,Canada,38366,27.2,26%,59:41:00,60.2125,39.6,46.5,84.4,80.2,86.9,2024
10703,178.0,Beijing Normal University,China,26439,14.4,9%,NaN,60.1800,57.7,45.8,77.5,67.6,52.3,2024
10704,179.0,University of Exeter,United Kingdom,27190,16.6,28%,53:47:00,60.1680,33.5,42.5,95.7,52.2,95.5,2024
10705,180.0,Macquarie University,Australia,30371,51.7,22%,NaN,60.1455,36.7,44.2,87.4,90.9,88.6,2024
10706,181.0,Sapienza University of Rome,Italy,60522,22.2,9%,61:39:00,60.0050,53.5,48.1,77.9,85.4,46.5,2024

Show the average student population grouped by country

In [ ]:
df.groupby(['Country'])['Population'].mean()

Country
Algeria          33813.369863
Argentina        56339.222222
Armenia          13838.000000
Australia        23558.761755
Austria          11543.613636
                     ...
United States    22724.506640
Venezuela        28530.785714
Vietnam          42765.739130
Zambia           18939.500000
Zimbabwe         22853.000000
Name: Population, Length: 108, dtype: float64

Show the total number of students grouped by country

In [ ]:
df.groupby(['Country'])['Population'].sum()

Country
Algeria           2468376
Argentina         1521159
Armenia             13838
Australia         7515245
Austria           1015838
                   ...
United States    34223107
Venezuela          399431
Vietnam            983612
Zambia              37879
Zimbabwe            45706
Name: Population, Length: 108, dtype: int64

Find the university with the max overall score by country

In [ ]:
df.groupby(['Country'])['Overall Score'].max()

Country
Algeria          43.7325
Argentina        23.5600
Armenia          21.0980
Australia        79.1865
Austria          65.2270
                  ...
United States    97.9720
Venezuela        18.5775
Vietnam          43.9850
Zambia           41.2125
Zimbabwe         26.9375
Name: Overall Score, Length: 108, dtype: float64

Show the average student to staff ratio grouped by country

In [ ]:
df.groupby(['Country'])['Students to Staff Ratio'].mean()

Country
Algeria          21.264384
Argentina        17.377778
Armenia           8.000000
Australia        29.062382
Austria          15.939773
                   ...
United States    14.629349
Venezuela        16.450000
Vietnam          21.891304
Zambia           22.900000
Zimbabwe         23.200000
Name: Students to Staff Ratio, Length: 108, dtype: float64